services:
  workspace:
    build:
      context: services/workspace
    cap_add:
      - SYS_PTRACE
    tty: true
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/workspace/home:/root

  php-fpm:
    build:
      context: services/php-fpm
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    expose:
      - "9000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: services/frontend
    expose:
      - "3000"
      - "24678"
    ports:
      - "24678:24678"
    volumes:
      - ${FRONTEND_CODE_PATH_HOST}:${FRONTEND_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/frontend/home:/root

  db:
    build: services/percona
    platform: linux/x86_64
    volumes:
      - ${DATA_PATH_HOST}/db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "3306"

  redis:
    build: services/redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    expose:
      - "6379"

  nginx:
    build: services/nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_HOST_CONFIG_PATH}:/etc/nginx/sites-available/
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm